const INCORRECT_DATA_ERROR = 400;
const AUTH_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const DOCUMENT_NOT_FOUND_ERROR = 404;
const CONFLICT_ERROR = 409;
const UNKNOWN_ERROR = 500;

module.exports = {
  INCORRECT_DATA_ERROR,
  DOCUMENT_NOT_FOUND_ERROR,
  UNKNOWN_ERROR,
  AUTH_ERROR,
  FORBIDDEN_ERROR,
  CONFLICT_ERROR,
};
